sonar.projectKey=Dhanushri26_JewelCart
sonar.organization=dhanushri26
sonar.host.url=https://sonarcloud.io
sonar.sources=frontend/src,backend
sonar.tests=tests/backend,frontend
sonar.test.inclusions=tests/**/*.test.*
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=backend/**,frontend/src/pages/**,frontend/src/components/**,frontend/src/layouts/**,frontend/src/context/**,frontend/src/routes/**,frontend/src/services/**,frontend/src/main.jsx,frontend/src/App.jsx,frontend/src/amplifyConfig.js
sonar.sourceEncoding=UTF-8