sonar.projectKey=JewelCart
sonar.organization=dhanushri26
sonar.host.url=https://sonarcloud.io
sonar.sources=frontend/src,backend
sonar.tests=tests
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=frontend/src/**/*.{jsx,tsx},backend/**/*.{json,md}
sonar.test.inclusions=tests/**/*.test.*
sonar.sourceEncoding=UTF-8

