sonar.projectKey=Dhanushri26_JewelCart
sonar.organization=dhanushri26
sonar.host.url=https://sonarcloud.io

sonar.sources=frontend/src,backend
sonar.tests=tests/backend,frontend

sonar.test.inclusions=tests/**/*.test.*

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.coverage.exclusions=\
frontend/src/main.jsx,\
frontend/src/App.jsx,\
frontend/src/amplifyConfig.js,\
frontend/src/routes/**,\
frontend/src/layouts/**

sonar.sourceEncoding=UTF-8